# fly.toml app configuration file generated for ayato-tips-nixpacks on 2023-10-17T04:08:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ayato-tips-nixpacks"
primary_region = "nrt"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
	WP_HOME='https://ayato-tips-nixpacks.fly.dev'
	WP_SITEURL="${WP_HOME}/wp"
